server:
  port: 3080
  servlet:
    session:
      cookie:
        name: lingu_image_hosting


logging:
  charset:
    console: UTF-8
  level:
    space.lingu.imagehosting: debug

spring:
  security:
    user:
      name: Lingu
      password: ImageHosting@0937
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: noreply@lingu.space
    password: MentalOut_010
