server:
  port: 3080
  servlet:
    session:
      cookie:
        name: lingu_image_hosting

logging:
  charset:
    console: UTF-8
  level:
    space.lingu.imagehosting: debug
    web: debug
    org.springframework.security: debug

spring:
  application:
    name: Lingu Image Hosting
  security:
    user:
      name: Lingu
      password: ImageHosting@0937
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: disable
    password: disable

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  cache:
    type: caffeine

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 0.3.1
  application-description:
  host: http://localhost:${server.port}

web-url:
  backend-url: http://localhost:${server.port}
  frontend-url: http://localhost:3090
  allowed-origins:
    - http://localhost:3090
    - http://127.0.0.1:3090
    - http://localhost:${server.port}

hdfs:
  url: hdfs://192.168.44.132:9000
